class StatesMXList{
  final List<Map<String, dynamic>> mxStatesList = [
    { "id": 1, "estado": "Aguascalientes", "abreviatura": "AGS" },
    { "id": 2, "estado": "Baja California", "abreviatura": "BC" },
    { "id": 3, "estado": "Baja California Sur", "abreviatura": "BCS" },
    { "id": 4, "estado": "Campeche", "abreviatura": "CAMP" },
    { "id": 5, "estado": "Chiapas", "abreviatura": "CHIS" },
    { "id": 6, "estado": "Chihuahua", "abreviatura": "CHIH" },
    { "id": 7, "estado": "Ciudad de México", "abreviatura": "CDMX" },
    { "id": 8, "estado": "Coahuila", "abreviatura": "COAH" },
    { "id": 9, "estado": "Colima", "abreviatura": "COL" },
    { "id": 10, "estado": "Durango", "abreviatura": "DGO" },
    { "id": 11, "estado": "Guanajuato", "abreviatura": "GTO" },
    { "id": 12, "estado": "Guerrero", "abreviatura": "GRO" },
    { "id": 13, "estado": "Hidalgo", "abreviatura": "HGO" },
    { "id": 14, "estado": "Jalisco", "abreviatura": "JAL" },
    { "id": 15, "estado": "México", "abreviatura": "MEX" },
    { "id": 16, "estado": "Michoacán", "abreviatura": "MICH" },
    { "id": 17, "estado": "Morelos", "abreviatura": "MOR" },
    { "id": 18, "estado": "Nayarit", "abreviatura": "NAY" },
    { "id": 19, "estado": "Nuevo León", "abreviatura": "NL" },
    { "id": 20, "estado": "Oaxaca", "abreviatura": "OAX" },
    { "id": 21, "estado": "Puebla", "abreviatura": "PUE" },
    { "id": 22, "estado": "Querétaro", "abreviatura": "QRO" },
    { "id": 23, "estado": "Quintana Roo", "abreviatura": "QROO" },
    { "id": 24, "estado": "San Luis Potosí", "abreviatura": "SLP" },
    { "id": 25, "estado": "Sinaloa", "abreviatura": "SIN" },
    { "id": 26, "estado": "Sonora", "abreviatura": "SON" },
    { "id": 27, "estado": "Tabasco", "abreviatura": "TAB" },
    { "id": 28, "estado": "Tamaulipas", "abreviatura": "TAMPS" },
    { "id": 29, "estado": "Tlaxcala", "abreviatura": "TLAX" },
    { "id": 30, "estado": "Veracruz", "abreviatura": "VER" },
    { "id": 31, "estado": "Yucatán", "abreviatura": "YUC" },
    { "id": 32, "estado": "Zacatecas", "abreviatura": "ZAC" },
    { "id": 33, "estado": "Lugar no registrado", "abreviatura": "DES" }
  ];
}